### ISSUE TITLE
Librepod library: add more robust mechanism to provide IngressRoute rules via the values.yaml

### ISSUE THREAD

**Issue by cyxou** [librepod/charts#32]
Currently it is not possible to add some fancy rules to IngressRoute via the values.yaml file in order to produce yaml like this:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: wg-easy
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: PathPrefix(`/`)
      priority: 1
      services:
        - name: wg-easy
          port: 80
          passHostHeader: true
    - kind: Rule
      match: Host(`wireguard.libre.pod`)
      services:
        - name: wg-easy
          port: 80 
          passHostHeader: true
```
